---
title: "Open HFD5 File"
author: "R. Remigio"
date: "June 20, 2016"
output: html_document
---
## About this code


```{r load-libraries}
## load libraries

library(raster)
library(rhdf5)
library(rgdal)
library(devtools)

```

## Let's Open A File- Use ".." to move upstream a directory!
```{r select-file}
# import data
f<-"../NEONdata/D17-California/TEAK/2013/spectrometer/reflectance/Subset3NIS1_20130614_100459_atmcor.h5"

##VIEW h5 structure
h5ls(f)

```

## Import Spatial Information

Spatial Information

```{r import-Spatial-Information}

# import spatial info

mapInfo <- h5read(f, 
                  "map info",
                  read.attributes = TRUE)
mapInfo

```

# Grab Reflectance Metadata

```{r get-reflectance-metadata}

# Read in reflectance data attributes
reflectInfo <- h5readAttributes(file = f, 
                                name = "Reflectance")
reflectInfo

# define scale factor

scaleFactor<-reflectInfo$`Scale Factor`

# define no data value
noDataValue<- as.numeric(reflectInfo$`data ignore value`)

```

## Import Data Dims

```{r import-dims}
# open file for viewing

fid <- H5Fopen(f)

# open the reflectance dataset
# Note- R begins indexing with row then column
# Whereas HDF5 starts with column then row
did<- H5Dopen(fid, "Reflectance")

#grab the dataset dimensions
# we will grab the space or structure of the data set
sid <- H5Dget_space(did)
sid

dims<-H5Sget_simple_extent_dims(sid)$size
dims

# close all open connections
H5Sclose(sid)
H5Dclose(did)
H5Fclose(fid)

```


## Read In Reflectance Data
Notes Goes here! It sure does...

```{r read-data}

#extract slice of H5 File (data cube)

#extract Band56 from data cube
b56 <- h5read(f, 
              "Reflectance", 
              index=list(1:dims[1], 1:dims[2], 56)) # bring in XYZ coords (column, row,               band (z-dim)). All x and y, and band slice (56)
b56

class(b56)

## Data has no shape- will need to convert it to a shapefile or something spatially
## referenced
```

## Convert Data to Matrix

```{r convert-matrix}
b56<- b56[,,1] ## declare '1' to indicate a single 'band'

# let's plot some data FINALLY
image(b56)

image(log(b56), main=("log transformed data")) ## data is skewed, log transforming brings pixel brightness to a tighter range. Less brighter
      
hist(log(b56))

## data stored as integer to save on space
```

```{r data-clean-up}

# assign no data values to object

b56[b56 == noDataValue] <- NA

# apply scale factor
b56 <- b56/scaleFactor
```

## Transpose Data

```{r transpose-data}

b56<- t(b56)
image(log(b56))

```

## Create Spatial Extent

```{r create-spatial-extent}
# split element using comma (string split!)
# split out Map Info object
# also include 'unlist' to delist

mapInfo<-strsplit(mapInfo, ",")
mapInfo<-unlist(mapInfo)
mapInfo

# value at 3 element in list
mapInfo[3]

# define upper left hand corner coordinate (Xmin, YMax)
xMin<-as.numeric(mapInfo[4])
yMax<-as.numeric(mapInfo[5])

# get spatial resolution

xres<- as.numeric(mapInfo[6])
yres<-as.numeric(mapInfo[7])

# Calculate Xmax and Ymin

xMax<- xMin + (dims[1]* xres) ## FOLLOWUP HERE
yMin<- yMax - (dims[2]* yres)

```

##Create Spatial Extent

```{r create-extent}

#create extent object

rasExt<- extent(xMin, xMax, 
                yMin, yMax)

rasExt

#create raster object
b56r<- raster(b56,
              crs=CRS("+init=epsg:32611"))

extent(b56r)<-rasExt

#plot data
plot(b56r, main="spatially referenced data")
```

# Import NEON Functions- DO IT FASTER (and easier!
```{r import-using-functions}
#install.package("devtools")
library(devtools)
#install_github("lwasser/neon-aop-package/neonAOP")
library(neonAOP)

# use open band function to view data
b55<-open_band(f, 55, 32611)

## import several bands (raster stacks)

bands<- c(58, 34, 19) ## blue, green, red (low to high)

# create raster stack

RGBStack <- create_stack(f, 
                         bands=bands, epsg=32611)

RGBStack

plot(RGBStack)

# plot the output, use a linear stretch to make it look nice
plotRGB(RGBStack,
        stretch='lin')



# CIR create  alist of the bands
bands <- c(90, 34, 19)

CIRStack <- create_stack(f, 
                         bands, 
                         epsg=32611)
plotRGB(CIRStack, stretch='lin',
           title="Color Infrared (CIR) Image")

```

